### ISSUE TITLE
os.exit() crashes other plugins and NPP

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#15] opened 2016-03-05 13:08 UTC
os.exit() crashes other plugins and Notepad++ itself

**Comment by dail8859** [comment] 2016-03-05 13:12
That doesn't surprise me and I wouldn't expect it to gracefully shutdown Notepad++

**Comment by dail8859** [comment] 2016-03-05 17:16
I'll have to think about this. Some options to myself on how to handle this...

1. Leave it as-is and assume the user knows what they are doing. This is no different than a plugin developer calling `exit()` in their plugin, it is guaranteed to have bad side effects.
2. Remove `os.exit()`. Easy to do but this would probably mean going through the rest of the standard libraries to see if anything else needs removed. Then of course documenting all removed functionality and hope the user reads it.
3. Try to replace/wrap any "bad" library calls so they behave better. This sounds like alot of work and some might not be fixable.

**Comment by OwnageIsMagic** [comment] 2016-03-05 20:19
I think it should be left as-is, since it works as it mean to be if no plugins of some sort installed.
It could be usefull in script like: 

> Save all, execute `shutdown /s /t 0` and exit

Just add notice in documentation that using `os.exit()` may crash N++

**Comment by OwnageIsMagic** [comment] 2016-03-05 21:02
it shows the same error on different plugins (and this plugins have very simillar layouts)
it means that bug in popular plugin template or loader, so it would be nice to report it somewhere

**Comment by dail8859** [comment] 2016-03-05 21:07
It's *not* a bug. Calling `os.exit()` is immediately killing the process which should not be done. Notepad++ should be the process to decide to shut down and take the appropriate measures (save files, clean up memory, clean up plugins) before stopping.

**Comment by OwnageIsMagic** [comment] 2016-03-05 21:29
Without some other plugins it closes gracefully with exit status 0
It means that problem in commonly used component (I suspect wrapper for .Net) for plugin creation, so I left note for myself to find it oneday

**Comment by dail8859** [comment] 2016-03-05 21:37
You get an exit status of 0 because by default calling `os.exit()` [returns 0](http://www.lua.org/manual/5.3/manual.html#pdf-os.exit). That doesn't mean things were OK, it just means the application some how decided to return 0, and in this case was by calling `os.exit()`. If you call `os.exit(1)` then the exit status will return 1.

Again...it is not a bug. I might as well close the issue as well since I'm fine leaving it as-is.

**Closed by dail8859** 2016-03-05 21:37 UTC

**Comment by OwnageIsMagic** [comment] 2016-03-05 21:52
I don`t try that there is some problem in Your code.
Calling `os.exit(25)` sets exit code to `25` that means that it was intentional (not some how) to set zero as exit code.

**Comment by dail8859** [comment] 2016-03-05 21:57
I understand. What I'm saying is the *actual* bug is using `os.exit()`. You'll notice that if Notepad++ doesn't crash, it does not have a chance to save any modified files at all because it doesn't have a chance.

**Comment by OwnageIsMagic** [comment] 2016-03-05 22:35
I think that exit without save is intented behaviour because it doesn\`t even calling lua finalizers.
It\`s a question for me why calling `std::exit(0)` => calling all destructors crashes app
