### ISSUE TITLE
Extend lua capabilities

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#20] opened 2016-03-06 09:43 UTC
Currently there is no way acces to Notepad++ internal variables (`$(FULL_CURRENT_PATH)`, `$(NAME_PART)`, etc.)
Also it's good idea to provide common routines (like list files in directory) through lua library calls. [Example](http://www.lua.org/pil/26.1.html).

**Comment by dail8859** [comment] 2016-03-06 12:31
> Currently there is no way acces to Notepad++ internal variables ($(FULL_CURRENT_PATH), $(NAME_PART), etc.)

All this and more is planned.

> Also it's good idea to provide common routines (like list files in directory) through lua library calls. 

This could quickly get out of hand of what is considered "common", which would mean alot of code to maintain, test, document. And there are libraries out there to do this type of common stuff. This won't be implemented at all.

On a side note, I don't actually know if it is possible to use 3rd party Lua libraries. I've never had a need currently. If there are changes that need made to LuaScript in order to support loading of 3rd party libraries then I wouldn't see a problem with that.

**Comment by ClaudiaFrank** [comment] 2016-03-06 19:12
If we talk about lua scripts being the libraries then it is already working.
@OwnageIsMagic you make sure that your package.path is correctly set.

**Comment by dail8859** [comment] 2016-03-06 19:19
> If we talk about lua scripts being the libraries then it is already working.

Yeah that is working assuming `package.path` is correct. The thing I've never tried is loading DLLs. It should work in theory but haven't had need for it.

**Comment by ClaudiaFrank** [comment] 2016-03-06 23:22
Unfortunattely only in theory, tried it with socket (core.dll). Module gets loaded but npp crashes.
Will try to find out what the problem is.

**Closed** 2016-03-17 13:22 UTC
